### ISSUE TITLE
add the settings to select the default view (list or group)

### ISSUE THREAD

**Issue by SVilgelm** [iulian-radu-at/vscode-tasks-sidebar#2]
Hi,

I would be great if you can add a setting for the default view type. I prefer the Group view, but it constantly changes to List after restarting of vscode

Thank you!

**Comment by iulian-radu-at** [comment]
Hi @SVilgelm,

Please try version 1.1.0 as I added there a setting for this.

Thanks,
Iulian

**Comment by iulian-radu-at** [comment]
Hi @SVilgelm,

You still use the 1.0.3 version. The setting is in Settings if you use version 1.1.0

Cheers,
Iulian

**Comment by SVilgelm** [comment]
oh, thank you! Had to restart vscode

**Comment by SVilgelm** [comment]
was confused by a version showed in readme :-)
